# Generated by Django 4.0.4 on 2022-04-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_place_date_visited_place_notes_place_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='users',
            new_name='user',
        ),
    ]
